const TARGET=new Date('2026-08-13T00:00:00+05:30').getTime();
const $=s=>document.querySelector(s),screens=[...document.querySelectorAll('.screen')];
const go=id=>{screens.forEach(s=>{s.classList.remove('active','fade-in');s.classList.add('hidden-screen')});const n=document.getElementById(id);if(!n)return;n.classList.remove('hidden-screen');n.classList.add('active');requestAnimationFrame(()=>n.classList.add('fade-in'));scrollTo({top:0,behavior:'instant'})};
function countdown(){const diff=TARGET-Date.now();if(diff<=0){$('#countdown').innerHTML='<div class="unit"><b>00</b><span>UNLOCKED</span></div>';unlock();return}const d=Math.floor(diff/86400000),h=Math.floor(diff/3600000)%24,m=Math.floor(diff/60000)%60,s=Math.floor(diff/1000)%60;$('#countdown').innerHTML=[[d,'DAYS'],[h,'HOURS'],[m,'MIN'],[s,'SEC']].map(([n,l])=>`<div class="unit"><b>${String(n).padStart(2,'0')}</b><span>${l}</span></div>`).join('')}
let tempUnlocked=localStorage.getItem('tempBirthdayUnlock')==='1';function unlock(){tempUnlocked=true;localStorage.setItem('tempBirthdayUnlock','1');if($('#lockScreen')?.classList.contains('active'))setTimeout(()=>go('unlockScreen'),350)}$('#tempUnlock')?.addEventListener('click',unlock);countdown();setInterval(countdown,1000);if(tempUnlocked||Date.now()>=TARGET)go('unlockScreen');

document.addEventListener('click',e=>{const nav=e.target.closest('[data-go]');if(nav){go(nav.dataset.go);return}const portal=e.target.closest('[data-panel]');if(portal){openRoom(portal.dataset.panel);return}const source=e.target.closest('[data-source-month]');if(source)openHistoricalSource(source.dataset.sourceMonth)});
function openRoom(panel){go('panelScreen');document.querySelectorAll('.room').forEach(r=>r.classList.add('hidden'));document.getElementById(panel)?.classList.remove('hidden');if(panel==='memoryPanel')renderMemorySky()}
$('#backBtn')?.addEventListener('click',()=>go('partyScreen'));

// Protected cake ceremony — preserved as a core interaction.
let lit=false,wished=false;$('#lightBtn')?.addEventListener('click',()=>{if(lit)return;lit=true;$('#cakeWrap').classList.add('lit');$('#wishBtn').disabled=false;$('#lightBtn').textContent='Candles are glowing ✨';$('#cakeStatus').textContent='Take a breath. Make a wish. 🤫'});$('#wishBtn')?.addEventListener('click',()=>{if(!lit||wished)return;wished=true;$('#cakeWrap').classList.add('blown');$('#wishBtn').disabled=true;$('#cutBtn').disabled=false;$('#lightBtn').textContent='Wish made ✦';$('#cakeStatus').textContent='Wish made. Now cut the cake.'});$('#cutBtn')?.addEventListener('click',()=>{if(!wished)return;$('#cakeWrap').classList.add('cut');$('#cutBtn').disabled=true;$('#cakeStatus').textContent='✦ HAPPY BIRTHDAY ✦';makeConfetti();setTimeout(()=>go('celebrationScreen'),1700)});
function makeConfetti(){const box=$('#confetti');box.innerHTML='';for(let i=0;i<70;i++){const p=document.createElement('span');p.style.left=Math.random()*100+'%';p.style.setProperty('--x',`${Math.random()*180-90}px`);p.style.animationDelay=`${Math.random()*.45}s`;box.appendChild(p)}setTimeout(()=>box.innerHTML='',2600)}

const SUPABASE_URL='https://zvvkfevppxjtkziyubvc.supabase.co',SUPABASE_KEY='sb_publishable_q3--z_x6JLXWimyKF12wmQ_WQBTgc5X';
const dbHeaders=()=>({apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`});
async function db(path){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{headers:dbHeaders()});if(!r.ok)throw new Error(`Database ${r.status}`);return r.json()}
async function loadMedia(){try{const rows=await db('birthday_media?select=kind,title,url&published=eq.true&order=sort_order.asc,created_at.asc');const video=rows.find(x=>x.kind==='video'),voice=rows.find(x=>x.kind==='voice');if(video){$('#videoPlayer').src=video.url;$('#videoPlayerWrap').classList.add('has-media');$('#videoFileName').textContent=video.title||'Creator video'}if(voice){$('#audioPlayer').src=voice.url;$('#audioFileName').textContent=voice.title||'Creator voice note'}}catch(e){console.warn(e.message)}}
async function loadLetter(){try{const rows=await db('birthday_letters?select=title,body&order=created_at.desc&limit=1');if(rows[0]){$('#letterTitleDisplay').textContent=rows[0].title||'A little letter';$('#letterBodyDisplay').textContent=rows[0].body||''}}catch(e){console.warn(e.message)}}
loadMedia();loadLetter();

const MONTHS=['June 2025','July 2025','August 2025','September 2025','October 2025','November 2025','December 2025','January 2026','February 2026','March 2026','April 2026','May 2026','June 2026','July 2026'];
const FOLDERS={'June 2025':'2025-06','July 2025':'2025-07','August 2025':'2025-08','September 2025':'2025-09','October 2025':'2025-10','November 2025':'2025-11','December 2025':'2025-12','January 2026':'2026-01','February 2026':'2026-02','March 2026':'2026-03','April 2026':'2026-04','May 2026':'2026-05','June 2026':'2026-06','July 2026':'2026-07'};
function renderMemorySky(){const grid=$('#months');grid.innerHTML=MONTHS.map((m,i)=>`<article class="memory-month-card"><div class="memory-month-main"><span>${String(i+1).padStart(2,'0')}</span><b>${m}</b><small>empty constellation · creator-controlled</small></div><div class="memory-month-actions"><button class="source-btn" data-source-month="${m}">SOURCE ↗</button></div></article>`).join('');$('#memoryStatus').textContent='14 chapters · no assistant-generated memories';}
async function openHistoricalSource(month){const folder=FOLDERS[month];$('#sourceTitle').textContent=month;$('#sourceMeta').textContent='Loading historical source…';$('#sourceText').textContent='';$('#historicalSource').classList.remove('hidden');try{const r=await fetch(`https://raw.githubusercontent.com/akshatusing01/janmdinam-/main/HISTORY/${folder}/MONTH_EXTRACT.md`);if(!r.ok)throw new Error(`Source unavailable (${r.status})`);$('#sourceText').textContent=await r.text();$('#sourceMeta').textContent='Canonical HISTORY source extract';}catch(e){$('#sourceMeta').textContent='Source extract unavailable';$('#sourceText').textContent=e.message}}
$('#closeSource')?.addEventListener('click',()=>$('#historicalSource').classList.add('hidden'));
